#############################################################################
# Makefile for building: SimpleNetworkBridge
# Generated by qmake (2.01a) (Qt 4.8.2) on: Fri Aug 24 15:28:46 2018
# Project:  SimpleNetworkBridge.pro
# Template: subdirs
# Command: /qt/qt-everywhere-opensource-src-4.8.2/bin/qmake -o Makefile SimpleNetworkBridge.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /qt/qt-everywhere-opensource-src-4.8.2/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-tcpserver \
		sub-tcpclient \
		sub-udpclient \
		sub-htmllogger \
		sub-snbgui \
		sub-snbtests

tcpserver/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tcpserver/ || $(MKDIR) tcpserver/ 
	cd tcpserver/ && $(QMAKE) /root/Network/TcpIp4/UDPoverTCP/tcpserver/tcpserver.pro -o $(MAKEFILE)
sub-tcpserver-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tcpserver/ || $(MKDIR) tcpserver/ 
	cd tcpserver/ && $(QMAKE) /root/Network/TcpIp4/UDPoverTCP/tcpserver/tcpserver.pro -o $(MAKEFILE)
sub-tcpserver: tcpserver/$(MAKEFILE) FORCE
	cd tcpserver/ && $(MAKE) -f $(MAKEFILE)
sub-tcpserver-make_default: tcpserver/$(MAKEFILE) FORCE
	cd tcpserver/ && $(MAKE) -f $(MAKEFILE) 
sub-tcpserver-make_first: tcpserver/$(MAKEFILE) FORCE
	cd tcpserver/ && $(MAKE) -f $(MAKEFILE) first
sub-tcpserver-all: tcpserver/$(MAKEFILE) FORCE
	cd tcpserver/ && $(MAKE) -f $(MAKEFILE) all
sub-tcpserver-clean: tcpserver/$(MAKEFILE) FORCE
	cd tcpserver/ && $(MAKE) -f $(MAKEFILE) clean
sub-tcpserver-distclean: tcpserver/$(MAKEFILE) FORCE
	cd tcpserver/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tcpserver-install_subtargets: tcpserver/$(MAKEFILE) FORCE
	cd tcpserver/ && $(MAKE) -f $(MAKEFILE) install
sub-tcpserver-uninstall_subtargets: tcpserver/$(MAKEFILE) FORCE
	cd tcpserver/ && $(MAKE) -f $(MAKEFILE) uninstall
tcpclient/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) tcpclient/ || $(MKDIR) tcpclient/ 
	cd tcpclient/ && $(QMAKE) /root/Network/TcpIp4/UDPoverTCP/tcpclient/tcpclient.pro -o $(MAKEFILE)
sub-tcpclient-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) tcpclient/ || $(MKDIR) tcpclient/ 
	cd tcpclient/ && $(QMAKE) /root/Network/TcpIp4/UDPoverTCP/tcpclient/tcpclient.pro -o $(MAKEFILE)
sub-tcpclient: tcpclient/$(MAKEFILE) FORCE
	cd tcpclient/ && $(MAKE) -f $(MAKEFILE)
sub-tcpclient-make_default: tcpclient/$(MAKEFILE) FORCE
	cd tcpclient/ && $(MAKE) -f $(MAKEFILE) 
sub-tcpclient-make_first: tcpclient/$(MAKEFILE) FORCE
	cd tcpclient/ && $(MAKE) -f $(MAKEFILE) first
sub-tcpclient-all: tcpclient/$(MAKEFILE) FORCE
	cd tcpclient/ && $(MAKE) -f $(MAKEFILE) all
sub-tcpclient-clean: tcpclient/$(MAKEFILE) FORCE
	cd tcpclient/ && $(MAKE) -f $(MAKEFILE) clean
sub-tcpclient-distclean: tcpclient/$(MAKEFILE) FORCE
	cd tcpclient/ && $(MAKE) -f $(MAKEFILE) distclean
sub-tcpclient-install_subtargets: tcpclient/$(MAKEFILE) FORCE
	cd tcpclient/ && $(MAKE) -f $(MAKEFILE) install
sub-tcpclient-uninstall_subtargets: tcpclient/$(MAKEFILE) FORCE
	cd tcpclient/ && $(MAKE) -f $(MAKEFILE) uninstall
udpclient/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) udpclient/ || $(MKDIR) udpclient/ 
	cd udpclient/ && $(QMAKE) /root/Network/TcpIp4/UDPoverTCP/udpclient/udpclient.pro -o $(MAKEFILE)
sub-udpclient-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) udpclient/ || $(MKDIR) udpclient/ 
	cd udpclient/ && $(QMAKE) /root/Network/TcpIp4/UDPoverTCP/udpclient/udpclient.pro -o $(MAKEFILE)
sub-udpclient: udpclient/$(MAKEFILE) FORCE
	cd udpclient/ && $(MAKE) -f $(MAKEFILE)
sub-udpclient-make_default: udpclient/$(MAKEFILE) FORCE
	cd udpclient/ && $(MAKE) -f $(MAKEFILE) 
sub-udpclient-make_first: udpclient/$(MAKEFILE) FORCE
	cd udpclient/ && $(MAKE) -f $(MAKEFILE) first
sub-udpclient-all: udpclient/$(MAKEFILE) FORCE
	cd udpclient/ && $(MAKE) -f $(MAKEFILE) all
sub-udpclient-clean: udpclient/$(MAKEFILE) FORCE
	cd udpclient/ && $(MAKE) -f $(MAKEFILE) clean
sub-udpclient-distclean: udpclient/$(MAKEFILE) FORCE
	cd udpclient/ && $(MAKE) -f $(MAKEFILE) distclean
sub-udpclient-install_subtargets: udpclient/$(MAKEFILE) FORCE
	cd udpclient/ && $(MAKE) -f $(MAKEFILE) install
sub-udpclient-uninstall_subtargets: udpclient/$(MAKEFILE) FORCE
	cd udpclient/ && $(MAKE) -f $(MAKEFILE) uninstall
htmllogger/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) htmllogger/ || $(MKDIR) htmllogger/ 
	cd htmllogger/ && $(QMAKE) /root/Network/TcpIp4/UDPoverTCP/htmllogger/htmllogger.pro -o $(MAKEFILE)
sub-htmllogger-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) htmllogger/ || $(MKDIR) htmllogger/ 
	cd htmllogger/ && $(QMAKE) /root/Network/TcpIp4/UDPoverTCP/htmllogger/htmllogger.pro -o $(MAKEFILE)
sub-htmllogger: htmllogger/$(MAKEFILE) FORCE
	cd htmllogger/ && $(MAKE) -f $(MAKEFILE)
sub-htmllogger-make_default: htmllogger/$(MAKEFILE) FORCE
	cd htmllogger/ && $(MAKE) -f $(MAKEFILE) 
sub-htmllogger-make_first: htmllogger/$(MAKEFILE) FORCE
	cd htmllogger/ && $(MAKE) -f $(MAKEFILE) first
sub-htmllogger-all: htmllogger/$(MAKEFILE) FORCE
	cd htmllogger/ && $(MAKE) -f $(MAKEFILE) all
sub-htmllogger-clean: htmllogger/$(MAKEFILE) FORCE
	cd htmllogger/ && $(MAKE) -f $(MAKEFILE) clean
sub-htmllogger-distclean: htmllogger/$(MAKEFILE) FORCE
	cd htmllogger/ && $(MAKE) -f $(MAKEFILE) distclean
sub-htmllogger-install_subtargets: htmllogger/$(MAKEFILE) FORCE
	cd htmllogger/ && $(MAKE) -f $(MAKEFILE) install
sub-htmllogger-uninstall_subtargets: htmllogger/$(MAKEFILE) FORCE
	cd htmllogger/ && $(MAKE) -f $(MAKEFILE) uninstall
snbgui/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) snbgui/ || $(MKDIR) snbgui/ 
	cd snbgui/ && $(QMAKE) /root/Network/TcpIp4/UDPoverTCP/snbgui/snbgui.pro -o $(MAKEFILE)
sub-snbgui-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) snbgui/ || $(MKDIR) snbgui/ 
	cd snbgui/ && $(QMAKE) /root/Network/TcpIp4/UDPoverTCP/snbgui/snbgui.pro -o $(MAKEFILE)
sub-snbgui: snbgui/$(MAKEFILE) FORCE
	cd snbgui/ && $(MAKE) -f $(MAKEFILE)
sub-snbgui-make_default: snbgui/$(MAKEFILE) FORCE
	cd snbgui/ && $(MAKE) -f $(MAKEFILE) 
sub-snbgui-make_first: snbgui/$(MAKEFILE) FORCE
	cd snbgui/ && $(MAKE) -f $(MAKEFILE) first
sub-snbgui-all: snbgui/$(MAKEFILE) FORCE
	cd snbgui/ && $(MAKE) -f $(MAKEFILE) all
sub-snbgui-clean: snbgui/$(MAKEFILE) FORCE
	cd snbgui/ && $(MAKE) -f $(MAKEFILE) clean
sub-snbgui-distclean: snbgui/$(MAKEFILE) FORCE
	cd snbgui/ && $(MAKE) -f $(MAKEFILE) distclean
sub-snbgui-install_subtargets: snbgui/$(MAKEFILE) FORCE
	cd snbgui/ && $(MAKE) -f $(MAKEFILE) install
sub-snbgui-uninstall_subtargets: snbgui/$(MAKEFILE) FORCE
	cd snbgui/ && $(MAKE) -f $(MAKEFILE) uninstall
snbtests/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) snbtests/ || $(MKDIR) snbtests/ 
	cd snbtests/ && $(QMAKE) /root/Network/TcpIp4/UDPoverTCP/snbtests/snbtests.pro -o $(MAKEFILE)
sub-snbtests-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) snbtests/ || $(MKDIR) snbtests/ 
	cd snbtests/ && $(QMAKE) /root/Network/TcpIp4/UDPoverTCP/snbtests/snbtests.pro -o $(MAKEFILE)
sub-snbtests: snbtests/$(MAKEFILE) FORCE
	cd snbtests/ && $(MAKE) -f $(MAKEFILE)
sub-snbtests-make_default: snbtests/$(MAKEFILE) FORCE
	cd snbtests/ && $(MAKE) -f $(MAKEFILE) 
sub-snbtests-make_first: snbtests/$(MAKEFILE) FORCE
	cd snbtests/ && $(MAKE) -f $(MAKEFILE) first
sub-snbtests-all: snbtests/$(MAKEFILE) FORCE
	cd snbtests/ && $(MAKE) -f $(MAKEFILE) all
sub-snbtests-clean: snbtests/$(MAKEFILE) FORCE
	cd snbtests/ && $(MAKE) -f $(MAKEFILE) clean
sub-snbtests-distclean: snbtests/$(MAKEFILE) FORCE
	cd snbtests/ && $(MAKE) -f $(MAKEFILE) distclean
sub-snbtests-install_subtargets: snbtests/$(MAKEFILE) FORCE
	cd snbtests/ && $(MAKE) -f $(MAKEFILE) install
sub-snbtests-uninstall_subtargets: snbtests/$(MAKEFILE) FORCE
	cd snbtests/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: SimpleNetworkBridge.pro  /usr/local/Trolltech/Qt-4.8.2/mkspecs/linux-g++-64/qmake.conf /usr/local/Trolltech/Qt-4.8.2/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile SimpleNetworkBridge.pro
/usr/local/Trolltech/Qt-4.8.2/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-4.8.2/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile SimpleNetworkBridge.pro

qmake_all: sub-tcpserver-qmake_all sub-tcpclient-qmake_all sub-udpclient-qmake_all sub-htmllogger-qmake_all sub-snbgui-qmake_all sub-snbtests-qmake_all FORCE

make_default: sub-tcpserver-make_default sub-tcpclient-make_default sub-udpclient-make_default sub-htmllogger-make_default sub-snbgui-make_default sub-snbtests-make_default FORCE
make_first: sub-tcpserver-make_first sub-tcpclient-make_first sub-udpclient-make_first sub-htmllogger-make_first sub-snbgui-make_first sub-snbtests-make_first FORCE
all: sub-tcpserver-all sub-tcpclient-all sub-udpclient-all sub-htmllogger-all sub-snbgui-all sub-snbtests-all FORCE
clean: sub-tcpserver-clean sub-tcpclient-clean sub-udpclient-clean sub-htmllogger-clean sub-snbgui-clean sub-snbtests-clean FORCE
distclean: sub-tcpserver-distclean sub-tcpclient-distclean sub-udpclient-distclean sub-htmllogger-distclean sub-snbgui-distclean sub-snbtests-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-tcpserver-install_subtargets sub-tcpclient-install_subtargets sub-udpclient-install_subtargets sub-htmllogger-install_subtargets sub-snbgui-install_subtargets sub-snbtests-install_subtargets FORCE
uninstall_subtargets: sub-tcpserver-uninstall_subtargets sub-tcpclient-uninstall_subtargets sub-udpclient-uninstall_subtargets sub-htmllogger-uninstall_subtargets sub-snbgui-uninstall_subtargets sub-snbtests-uninstall_subtargets FORCE

sub-tcpserver-check: tcpserver/$(MAKEFILE)
	cd tcpserver/ && $(MAKE) -f $(MAKEFILE) check
sub-tcpclient-check: tcpclient/$(MAKEFILE)
	cd tcpclient/ && $(MAKE) -f $(MAKEFILE) check
sub-udpclient-check: udpclient/$(MAKEFILE)
	cd udpclient/ && $(MAKE) -f $(MAKEFILE) check
sub-htmllogger-check: htmllogger/$(MAKEFILE)
	cd htmllogger/ && $(MAKE) -f $(MAKEFILE) check
sub-snbgui-check: snbgui/$(MAKEFILE)
	cd snbgui/ && $(MAKE) -f $(MAKEFILE) check
sub-snbtests-check: snbtests/$(MAKEFILE)
	cd snbtests/ && $(MAKE) -f $(MAKEFILE) check
check: sub-tcpserver-check sub-tcpclient-check sub-udpclient-check sub-htmllogger-check sub-snbgui-check sub-snbtests-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

